site_name: OSCA
theme: 
  name: material
  icon:
    logo: material/robot-happy-outline
  favicon: https://cs.haohaha.cn/image/favicon.png
#     admonition:
  palette:
    - scheme: default # 日间模式
      primary: light green # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: light green
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
#   - navigation.prune
    - search.suggest
    - search.highlight
    - content.code.copy
    # Instant Loading
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # Anchor tracking
    - navigation.tracking
    
  language: zh

edit_uri: edit/main/docs

nav:
  - 首页: index.md
  - 关于团队: about/about.md
  - 招生简章: recruit/recruit.md
  - 人才培养:
    - guide/index.md
    - 2023届: 
      - 2023届-培养方案: guide/guide-2023.md
      - 2023届-考核标准: guide/assessment-2023.md
    - 2024届:
      - 2024届-培养方案: guide/guide-2024.md
      - 2024届-考核标准: guide/assessment-2024.md
      - C 程序示例 - 张浩: guide/C-sample-zh.md
  - 成员简介: members/members.md
  - 友情链接: members/links.md

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/extra_admonition.css # 自定义admonition

markdown_extensions:
    # Admonitions
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    # Icons, Emojis
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    # Formatting
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    # Diagrams
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  homepage: http://osca.haohaha.cn
  social: # icons
    - icon: simple/githubactions
      link: https://github.com/Haohahahaha/osca/actions
      name: GitHub Actions
## [bottom-left corner]
copyright: 
  <a href="https://beian.miit.gov.cn/" target="_blank">冀ICP备2024078994号</a><br/>
  <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=13020302001386" target="_blank">冀公网安备13020302001386号</a><br/>
  Copyright &copy; 2022-现在 浩哈哈哈哈_ # 左下角的版权声明